from .user import User
from .incubacion import Incubacion
from .nacimiento import Nacimiento
from .incubadora import Incubadora
from .nacedora import Nacedora
from .tipo_huevo import TipoHuevo
from .tipo_sensor import TipoSensor
from .detalles_nacimiento import DetallesNacimiento
from .detalles_incubacion import DetallesIncubacion
from .datos_sensor_incubadora import DatosSensorIncubadora
from .datos_sensor_nacedora import DatosSensorNacedora