from .user import User
from .incubacion import Incubacion
from .nacimiento import Nacimiento
from .incubadora import Incubadora
from .nacedora import Nacedora
from .tipo_huevo import Tipo_huevo
from .tipo_sensor import Tipo_sensor
from .detalles_nacimiento import Detalles_nacimiento
from .detalles_incubacion import Detalles_incubacion
from .datos_sensores_incubadora import Datos_sensores_incubadora
from .datos_sensores_nacedora import Datos_sensores_nacedora