@startuml Diagram de Clases
class Model {
 clase de SQLAlchemy
}

class User {
    id: int "PK"
    user_name: int
    password: str 
    role: str
}

class Proceso {
    id: int "PK"
    incubadora_asignada: int #"FK"id_incubadora
    fecha_entrada_inc: datetime 
    ent_araucana: int
    ent_camperos: int 
    ent_belichas: int 
    fecha_salida_inc: datetime 
    fert_araucanas: int 
    fert_camperos: int 
    fert_belichas: int 
    nacedora_asignada: int #"FK" id_nacedora
    fecha_entrada_nac: datetime 
    fecha_salida_nac: datetime
    nac_araucana: int 
    nac_camperos: int 
    nac_belichas: int 
    detalles: str 

}

class Incubadora {
    num_incubadora: int "PK"
    modelo: str 
    descripcion: str
}

class Nacedora {
    num_nacedora: int "PK"
    modelo: str 
    descripcion: str
}

class Sensores {
    num_sensor: str "PK"
    tipo_sensor: str
    asignacion: int
    description: str
}

Model <|-- User
Model <|-- Proceso
User <|-- Proceso

Proceso "1" o--o "1" Incubadora
Incubadora "m" o--o "n" Sensores

Proceso "1" o--o "1" Nacedora
Nacedora "m" o--o "n" Sensores

@enduml