@startuml Diagram de Clases
class Model {
 clase de SQLAlchemy
}

Class User {
    id: int "PK"
    user_name: int
    password: str 
    role: str
}

Class Incubacion {
    id: int "PK"
    fecha_entrada: datetime 
    fecha_salida: datetime 
    detalles: str 
    user_id: int "FK"
    incubadora_id: int #"FK"id_incubadora
}

Class Incubadora {
    id: int "PK"
    modelo: str 
    descripcion: str
}

class Detalle_incubacion {
    id: int "PK"
    incubacion_id: int "FK"
    tipo_huevo: str "FK"
    cant_huevos_inicial: int 
    cant_huevos_final: int 
}

Class Datos_sensores_incubadora {
    id: int "PK"
    incubacion_id: int "FK"
    tipo_sensor_id: int "FK"
    valor: int
    dia: datetime
}

Class Tipo_sensor {
    id: int "PK"
    tipo_sensor
}

Class Tipo_huevo {
    id: int "PK"
    tipo_huevo: str
    descripcion: str
}

Class Nacimiento {
    id: int "PK"
    fecha_entrada: datetime 
    fecha_salida: datetime 
    detalles: str 
    user_id: int "FK"
    nacedora_id: int "FK"
}

Class Nacedora {
    id: int "PK"
    modelo: str 
    descripcion: str
}

class Detalle_nacimiento {
    id: int "PK"
    nacimiento_id: int "FK"
    tipo_huevo: str "FK"
    cant_huevos_inicial: int 
    cant_huevos_final: int 
}

Class Datos_sensores_nacedora {
    id: int "PK"
    nacimiento_id: int "FK"
    tipo_sensor_id: int "FK"
    valor: int
    dia: datetime
}

Model <|-- User
Model <|-- Incubacion
Model <|-- Incubadora
Model <|-- Detalle_incubacion
Model <|-- Datos_sensores_incubadora
Model <|-- Tipo_sensor
Model <|-- Tipo_huevo
Model <|-- Nacimiento
Model <|-- Nacedora
Model <|-- Detalle_nacimiento
Model <|-- Datos_sensores_nacedora

User "1" o--o "N" Incubacion
Incubadora "1" o--o "N" Incubacion
Incubacion "1" o--o "N" Detalle_incubacion
Incubacion "1" o--o "N" Datos_sensores_incubadora
Tipo_huevo "1" o--o "N" Detalle_incubacion 
Tipo_sensor "1" o--o "N" Datos_sensores_incubadora

User "1" o--o "N" Nacedora
Nacedora "1" o--o "N" Nacimiento
Nacimiento "1" o--o "N" Detalle_nacimiento
Nacimiento "1" o--o "N" Datos_sensores_nacedora
Tipo_huevo "1" o--o "N" Detalle_nacimiento
Tipo_sensor "1" o--o "N" Datos_sensores_nacedora

@enduml